### ISSUE TITLE
Does not save changes to 2 meshes at the same time.

### ISSUE THREAD

**Issue by reicou** [ShalltyB/BlendshapeCreator#4]
Hello, first of all, I wanted to thank you for this amazing tool that for me revolutionizes the way I use Koikatsu. And now I explain the problem:

I have created sliders in different meshes of the same character. For example, in the top and skirt of this character:

![1](https://github.com/user-attachments/assets/0636af49-6e83-40d0-9c0b-af8f153182e2)

However, although I apply the sliders to the character and then save it, when I load the character, only the sliders of one of the meshes (in this case the top) are applied, and not those of the other mesh (the skirt). The skirt sliders appear at 0% when loading the character and are not saved even if I set them to 100% and save the character.

The most curious thing is that the first character with which I use the tool it saved the changes in two different meshes at the same time, but since then, in all the other characters it never saves the changes in 2 different meshes at the same time. 

Finally, a suggestion; would it be possible to open the BlendshapeCreator menu in the Studio? I have tried with the shortcut but it only works in the maker.

**Comment by ShalltyB** [comment]
hi, this version should fix the problem that you have, and BlendshapeCreator is already available in studio, the default keybind is (CTRL + B), check in Configuration Manager if there is any other plugin with colliding keybinds.

[blendshapecreator.zip](https://github.com/user-attachments/files/16790780/blendshapecreator.zip)

**Comment by reicou** [comment]
I can confirm that now it works perfectly, and also I have changed the keyboard shortcut for the studio and now I can see the menu, it must be a key conflict, as you said.

I just want to tell you again, thank you very, very, very much for creating this tool. I am totally serious, without any doubt that this is the most important, most revolutionary, most useful, and possibly most underrated mod for Koikatsu. 

Not only can you change the clothing mesh, but any mesh on the character. You can create extremely detailed faces and bodies, edit down to the millimeter every part of the character, and their outfits. Simply put, it changes the game so radically, that it looks like a completely different game. This tool, using the incredible capabilities of Blender, gives you absolute freedom to create whatever you want with total precision. 

It is simply the best mod ever created for Koikatsu. Thank you from the bottom of my heart.
